export const FORMATIONS_DETAIL = {
  '6v6': {
    '2-2-1': {
      FW: null,
      MF1: null,
      MF2: null,
      DF1: null,
      DF2: null,
      GK: null,
    },
    '2-1-2': {
      FW1: null,
      FW2: null,
      MF: null,
      DF1: null,
      DF2: null,
      GK: null,
    },
    '1-3-1': {
      FW: null,
      MF1: null,
      MF2: null,
      MF3: null,
      DF: null,
      GK: null,
    },
  },
  '5v5': {
    '2-0-2': {
      FW1: null,
      FW2: null,
      DF1: null,
      DF2: null,
      GK: null,
    },
    '2-1-1': {
      FW: null,
      MF: null,
      DF1: null,
      DF2: null,
      GK: null,
    },
    '1-2-1': {
      FW: null,
      MF1: null,
      MF2: null,
      DF: null,
      GK: null,
    },
    '1-1-2': {
      FW1: null,
      FW2: null,
      MF: null,
      DF: null,
      GK: null,
    },
  },
};

export const LEVEL_DISTRIBUTION = {
  '비기너3 이하': {
    스타터1: 0,
    스타터2: 0,
    스타터3: 0,
    비기너1: 0,
    비기너2: 0,
    비기너3: 0,
  },
  '세미프로1 이상': {
    세미프로1: 0,
    세미프로2: 0,
    세미프로3: 0,
    프로1: 0,
    프로2: 0,
    프로3: 0,
  },
  '모든 레벨': {
    스타터: 0,
    비기너: 0,
    아마추어: 0,
    세미프로: 0,
    프로: 0,
  },
};

export const TOWN_ALL = {
  서울특별시: {
    JONGNO_GU: '종로구',
    JUNG_GU: '중구',
    YONGSAN_GU: '용산구',
    SEONGDONG_GU: '성동구',
    GWANGJIN_GU: '광진구',
    DONGDAEMUN_GU: '동대문구',
    JUNGNANG_GU: '중랑구',
    SEONGBUK_GU: '성북구',
    GANGBUK_GU: '강북구',
    DOBONG_GU: '도봉구',
    NOWON_GU: '노원구',
    EUNPYEONG_GU: '은평구',
    SEODAMUN_GU: '서대문구',
    MAPO_GU: '마포구',
    YANGCHEON_GU: '양천구',
    GANGSEO_GU: '강서구',
    GURO_GU: '구로구',
    GEUMCHEON_GU: '금천구',
    YEONGDEUNGPO_GU: '영등포구',
    DONGJAK_GU: '동작구',
    GWANAK_GU: '관악구',
    SEOCHO_GU: '서초구',
    GANGNAM_GU: '강남구',
    SONGPA_GU: '송파구',
    GANGDONG_GU: '강동구',
  },
  부산광역시: {
    JUNG_GU: '중구',
    SEO_GU: '서구',
    DONG_GU: '동구',
    YEONGDO_GU: '영도구',
    BUSANJIN_GU: '부산진구',
    DONGNAE_GU: '동래구',
    NAM_GU: '남구',
    BUK_GU: '북구',
    HAEUNDAE_GU: '해운대구',
    SAHA_GU: '사하구',
    GEUMJEONG_GU: '금정구',
    GANGSEO_GU: '강서구',
    YEONJE_GU: '연제구',
    SUYEONG_GU: '수영구',
    SASANG_GU: '사상구',
    GIJANG_GUN: '기장군',
  },
  대구광역시: {
    JUNG_GU: '중구',
    DONG_GU: '동구',
    SEO_GU: '서구',
    NAM_GU: '남구',
    BUK_GU: '북구',
    SUSEONG_GU: '수성구',
    DALSEO_GU: '달서구',
    DALSEONG_GUN: '달성군',
  },
  인천광역시: {
    JUNG_GU: '중구',
    DONG_GU: '동구',
    MICHUHOL_GU: '미추홀구',
    YEONSU_GU: '연수구',
    NAMDONG_GU: '남동구',
    BUPYEONG_GU: '부평구',
    GYEYANG_GU: '계양구',
    SEO_GU: '서구',
    GANGHWA_GUN: '강화군',
    ONGJIN_GUN: '옹진군',
  },
  광주광역시: {
    DONG_GU: '동구',
    SEO_GU: '서구',
    NAM_GU: '남구',
    BUK_GU: '북구',
    GWANGSAN_GU: '광산구',
  },
  대전광역시: {
    DONG_GU: '동구',
    JUNG_GU: '중구',
    SEO_GU: '서구',
    YOOSEONG_GU: '유성구',
    DAEDEOK_GU: '대덕구',
  },
  울산광역시: {
    JUNG_GU: '중구',
    NAM_GU: '남구',
    DONG_GU: '동구',
    BUK_GU: '북구',
    ULJU_GUN: '울주군',
  },
  세종특별자치시: {
    SEJONG: '세종특별자치시',
  },
  경기도: {
    SUWON: '수원시',
    SEONGNAM: '성남시',
    GOYANG: '고양시',
    YONGIN: '용인시',
    BUCHEON: '부천시',
    ANSAN: '안산시',
    ANYANG: '안양시',
    NAMYANGJU: '남양주시',
    HWASEONG: '화성시',
    PYEONGTAEK: '평택시',
    UIJEONGBU: '의정부시',
    SIHEUNG: '시흥시',
    PAJU: '파주시',
    GWANGMYEONG: '광명시',
    GIMPO: '김포시',
    GUNPO: '군포시',
    GWANGJU: '광주시',
    ICHEON: '이천시',
    YANGJU: '양주시',
    OSAN: '오산시',
    GURI: '구리시',
    ANSEONG: '안성시',
    POCHEON: '포천시',
    UIWANG: '의왕시',
    HANAM: '하남시',
    YEOJU: '여주시',
    YANGPYEONG: '양평군',
    DONGDUCHEON: '동두천시',
    GWACHEON: '과천시',
    GAPYEONG_GUN: '가평군',
    YEONCHEON_GUN: '연천군',
  },
  강원도: {
    CHUNCHEON: '춘천시',
    WONJU: '원주시',
    GANGNEUNG: '강릉시',
    DONGHAE: '동해시',
    TAEBAEK: '태백시',
    SOKCHO: '속초시',
    SAMCHEOK: '삼척시',
    HONGCHEON_GUN: '홍천군',
    HOENGSEONG_GUN: '횡성군',
    YEONGWOL_GUN: '영월군',
    PYEONGCHANG_GUN: '평창군',
    JEONGSEON_GUN: '정선군',
    CHERWON_GUN: '철원군',
    HWACHEON_GUN: '화천군',
    YANGGU_GUN: '양구군',
    INJE_GUN: '인제군',
    GOSEONG_GUN: '고성군',
    YANGYANG_GUN: '양양군',
  },
  충청북도: {
    CHEONGJU: '청주시',
    CHUNGJU: '충주시',
    JECHEON: '제천시',
    BOEUN_GUN: '보은군',
    OKCHEON_GUN: '옥천군',
    YEONGDONG_GUN: '영동군',
    JINCHEON_GUN: '진천군',
    GOESAN_GUN: '괴산군',
    EUMSEONG_GUN: '음성군',
    DANYANG_GUN: '단양군',
    JEUNGPYEONG_GUN: '증평군',
  },
  충청남도: {
    CHEONAN: '천안시',
    GONGJU: '공주시',
    BORYEONG: '보령시',
    ASAN: '아산시',
    SEOSAN: '서산시',
    NONSAN: '논산시',
    GYERYONG: '계룡시',
    DANGJIN: '당진시',
    GEUMSAN_GUN: '금산군',
    BUYEO_GUN: '부여군',
    SEOCHEON_GUN: '서천군',
    CHEONGYANG_GUN: '청양군',
    HONGSEONG_GUN: '홍성군',
    YESAN_GUN: '예산군',
    TAEAN_GUN: '태안군',
  },
  전라북도: {
    JEONJU: '전주시',
    GUNSAN: '군산시',
    IKSAN: '익산시',
    JEONGEUP: '정읍시',
    NAMWON: '남원시',
    GIMJE: '김제시',
    WANJU_GUN: '완주군',
    JINAN_GUN: '진안군',
    MUJU_GUN: '무주군',
    JANGSU_GUN: '장수군',
    IMSIL_GUN: '임실군',
    SUNCHANG_GUN: '순창군',
    GOCHANG_GUN: '고창군',
    BUAN_GUN: '부안군',
  },
  전라남도: {
    MOKPO: '목포시',
    YEOSU: '여수시',
    SUNCHEON: '순천시',
    NAJU: '나주시',
    GWANGYANG: '광양시',
    DAMYANG_GUN: '담양군',
    GOKSEONG_GUN: '곡성군',
    GURYE_GUN: '구례군',
    GOHEUNG_GUN: '고흥군',
    BOSEONG_GUN: '보성군',
    HWASUN_GUN: '화순군',
    JANGHEUNG_GUN: '장흥군',
    GANGJIN_GUN: '강진군',
    HAENAM_GUN: '해남군',
    YEONGAM_GUN: '영암군',
    MUNAN_GUN: '무안군',
    HAMPYEONG_GUN: '함평군',
    YOUNGGWANG_GUN: '영광군',
    JANGSEONG_GUN: '장성군',
    WANDO_GUN: '완도군',
    JINDO_GUN: '진도군',
    SINAN_GUN: '신안군',
  },
  경상북도: {
    POHANG: '포항시',
    GYEONGJU: '경주시',
    GIMCHEON: '김천시',
    ANDONG: '안동시',
    GUMI: '구미시',
    YEONGJU: '영주시',
    YEONGCHEON: '영천시',
    SANGJU: '상주시',
    MUNGYEONG: '문경시',
    GYEONGSAN: '경산시',
    GUNWI_GUN: '군위군',
    UISEONG_GUN: '의성군',
    CHEONGSONG_GUN: '청송군',
    YEONGYANG_GUN: '영양군',
    YEONGDEOK_GUN: '영덕군',
    CHEONGDO_GUN: '청도군',
    GORYEONG_GUN: '고령군',
    SEONGJU_GUN: '성주군',
    CHILGOK_GUN: '칠곡군',
    YECHEON_GUN: '예천군',
    BONGHWA_GUN: '봉화군',
    ULJIN_GUN: '울진군',
    ULLEUNG_GUN: '울릉군',
  },
  경상남도: {
    CHANGWON: '창원시',
    JINJU: '진주시',
    TONGYEONG: '통영시',
    SACHEON: '사천시',
    GIMHAE: '김해시',
    MIRYANG: '밀양시',
    GEOJE: '거제시',
    YANGSAN: '양산시',
    UIRYEONG_GUN: '의령군',
    HAMAN_GUN: '함안군',
    CHANGNYEONG_GUN: '창녕군',
    GOSEONG_GUN: '고성군',
    NAMHAE_GUN: '남해군',
    HADONG_GUN: '하동군',
    SANCHEONG_GUN: '산청군',
    HAMYANG_GUN: '함양군',
    GEOCHANG_GUN: '거창군',
    HAPCHEON_GUN: '합천군',
  },
  제주특별자치도: { JEJU: '제주시', SEOGWIPO: '서귀포시' },
};
